use github actions bot user in benchmark workflow
AcademySoftwareFoundation/rez pull request #1319
Opened 2022-06-08 11:12 UTC by nerdvegas

Closes #1318

2022-06-08 15:14 UTC, JeanChristopheMorinPerso requested changes
Looks great, just left a little suggestion.

2022-06-08 23:43 UTC, nerdvegas commented on CONTRIBUTING.md
> +Rez enforces Developer Certificate of Origin (DCO) on all commits, as per ASWF guidelines.
What timing jc! Github now has native DCO support, and aswf has activated it as of yesterday: https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/.

I'll add this link instead, cheers

2022-06-08 23:47 UTC, JeanChristopheMorinPerso commented on CONTRIBUTING.md
> +Rez enforces Developer Certificate of Origin (DCO) on all commits, as per ASWF guidelines.
What they announced is slightly different though as it only applies to Web commits.

2022-06-08 23:48 UTC, JeanChristopheMorinPerso commented on CONTRIBUTING.md
> +Rez enforces Developer Certificate of Origin (DCO) on all commits, as per ASWF guidelines.
So I'd still link to the probot DCO page.

2022-06-09 00:07 UTC, nerdvegas commented
*On web-based commits... I completely missed that, you're right. That's a
little underwhelming.



On Thu, 9 June 2022, 09:48 Jean-Christophe Morin, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/AcademySoftwareFoundation/rez/pull/1319#discussion_r892954344>
> :
>
> >
> -The Windows tests currently build a Python image for each version to test. Each is based on a common
> -base image. Any changes to the following Docker images sources should be a separate commit:
> +Rez enforces Developer Certificate of Origin (DCO) on all commits, as per ASWF guidelines.
>
> So I'd still link to the probot DCO page.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AcademySoftwareFoundation/rez/pull/1319#discussion_r892954344>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMOUSTXDGNDEKIHXL5PN5TVOEWNHANCNFSM5YGERDAQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-09 00:26 UTC, JeanChristopheMorinPerso approved these changes

2022-06-14 11:15 UTC, merged