working with embedded python scanning rezplugins
AcademySoftwareFoundation/rez pull request #1359
Opened 2022-08-15 06:48 UTC by loonghao

This PR wants to improve working with embedded python scanning rez-plugins,
allow us to use [Pyinstaller ](https://github.com/pyinstaller/pyinstaller) and [PyOxidizer](https://github.com/indygreg/PyOxidizer) to make rez as a single application to deploy.

Below is a demo 
[rez-2.111.3.zip](https://github.com/AcademySoftwareFoundation/rez/files/9335504/rez-2.111.3.zip)

2022-08-19 03:57 UTC, nerdvegas commented
Fyi, pls ignore the flake8 fails, it's due to https://github.com/AcademySoftwareFoundation/rez/issues/1356. I don't know why this started happening... new versiond of flake8 maybe?

2022-09-21 11:41 UTC, nerdvegas commented
Hello, the linting fails have been fixed in https://github.com/AcademySoftwareFoundation/rez/pull/1369, could you re-merge with master so this PR can pass and unblock?

2022-09-21 11:41 UTC, nerdvegas requested changes

2022-09-21 11:41 UTC, nerdvegas commented on src/rez/plugin_managers.py
> +                    continue
requires comment with explanation

2022-09-22 04:21 UTC, nerdvegas approved these changes

2022-09-22 11:22 UTC, JeanChristopheMorinPerso approved these changes

2022-11-15 14:28 UTC, merged