Add `package_cache_async` flag.
AcademySoftwareFoundation/rez pull request #1452
Opened 2023-02-22 17:07 UTC by ttrently

Adds a `package_cachy_async` flag which allows users to run caching synchronously (blocking) or asynchronously from the config.

This setting is set to `True` by default in the rezconfig so that behavior should act as normal. Setting this to false will block the resolve until all packages have been cached successfully.

2023-02-22 17:39 UTC, JeanChristopheMorinPerso commented
Thanks @ttrently ! Can you follow the instructions at https://github.com/AcademySoftwareFoundation/rez/pull/1452/checks?check_run_id=11526898738 to fix the DCO check please?

2023-02-22 19:52 UTC, alx00x commented
A welcome addition. I want to add it should be implemented as a flag on `rez-env` command and an argument for `ResolvedContext` in the same manner how package caching itself can be disabled or enabled explicitly (config being a fallback).

For example:

```
rez env my_package --no-async
```

```
context = ResolvedContext(["my_package"], async_package_caching=False)
```

2023-02-23 01:03 UTC, JeanChristopheMorinPerso requested changes
Thanks @ttrently ! I think it could be a good idea to have a CLI flag, but I'm not sure what it should be named and to which commands it should apply. Any opinions?

2023-02-23 01:03 UTC, JeanChristopheMorinPerso commented on src/rez/rezconfig.py
> +# Enable package caching to run asynchronously during a resolve.
I find this hard to read. How about "set to false to always cache package payloads synchronously"?

2023-02-23 02:52 UTC, JeanChristopheMorinPerso commented
Also, the linter is complaining: https://github.com/AcademySoftwareFoundation/rez/actions/runs/4245498949/jobs/7387520293#step:5:1

2023-02-28 02:22 UTC, ttrently commented on src/rez/package_cache.py
> -                    [exe, "--daemon", self.path],
These are defined on line 457 but the `args` variable was never used unless I missed something. The `func` call on line 474 now uses that instead.

2023-02-28 02:31 UTC, JeanChristopheMorinPerso commented on src/rez/package_cache.py
> -                    [exe, "--daemon", self.path],
My bad. I got confused by how the diff looks like.

2024-03-07 01:46 UTC, closed without merging

2024-03-07 01:47 UTC, JeanChristopheMorinPerso commented
Loses in favor of #1679. @ttrently I'll make sure that you are marked as co-author.