Add Execution Policy setting to Powershell based shell plugins
AcademySoftwareFoundation/rez pull request #1505
Opened 2023-07-04 21:10 UTC by herronelou

Closes #1504 

This is a simple implementation of what I was requesting in #1504

I considered a different approach which would have been a bit more generic such as `shell_args`, which could have included the `-NoLogo` which is currently being inserted all the time. However, after reviewing the other shell plugins, I couldn't see the case for shell args for all of them, so I kept it localized to only doing exactly what I needed.

2023-09-06 23:05 UTC, maxnbk commented
I rebased to get the CI fixed, but the PR needs DCO fixed (commit signoff)

2023-09-09 17:23 UTC, JeanChristopheMorinPerso requested changes

2023-09-09 17:23 UTC, JeanChristopheMorinPerso commented on src/rezplugins/shell/_utils/powershell_base.py
> +        if execution_policy:
I am tempted to say that we should sanitize this a little bit. Maybe use a simple regex like `re.match(r'[a-zA-Z]+', execution_policy)` to make sure nobody injects a `;` or whatever weird thing that could lead to other even more weird to debug errors.

2023-09-09 19:04 UTC, maxnbk commented
I believe there is only like 5 executionpolicy types that are valid, can we
just list only those as valid and check for them / error if not?

On Sat, Sep 9, 2023 at 1:23 PM Jean-Christophe Morin <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/rezplugins/shell/_utils/powershell_base.py
> <https://github.com/AcademySoftwareFoundation/rez/pull/1505#discussion_r1320612931>
> :
>
> > @@ -202,6 +202,11 @@ def _record_shell(ex, files, bind_rez=True, print_msg=False):
>          # Suppresses copyright message of PowerShell and pwsh
>          cmd += ["-NoLogo"]
>
> +        # Powershell execution policy overrides
> +        execution_policy = self.settings.execution_policy
> +        if execution_policy:
>
> I am tempted to say that we should sanitize this a little bit. Maybe use a
> simple regex like re.match(r'[a-zA-Z]+', execution_policy) to make sure
> nobody injects a ; or whatever weird thing that could lead to other even
> more weird to debug errors.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AcademySoftwareFoundation/rez/pull/1505#pullrequestreview-1618674621>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPOE3QGRU2PLYPOHBHIEX3XZSQZPANCNFSM6AAAAAAZ6ESIMM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-09-09 19:17 UTC, herronelou commented
Yes that would be pretty easy to do and prevent injections

On Sat, Sep 9, 2023, 12:04 Stephen Mackenzie ***@***.***>
wrote:

> I believe there is only like 5 executionpolicy types that are valid, can
> we
> just list only those as valid and check for them / error if not?
>
> On Sat, Sep 9, 2023 at 1:23 PM Jean-Christophe Morin <
> ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> > ------------------------------
> >
> > In src/rezplugins/shell/_utils/powershell_base.py
> > <
> https://github.com/AcademySoftwareFoundation/rez/pull/1505#discussion_r1320612931>
>
> > :
> >
> > > @@ -202,6 +202,11 @@ def _record_shell(ex, files, bind_rez=True,
> print_msg=False):
> > # Suppresses copyright message of PowerShell and pwsh
> > cmd += ["-NoLogo"]
> >
> > + # Powershell execution policy overrides
> > + execution_policy = self.settings.execution_policy
> > + if execution_policy:
> >
> > I am tempted to say that we should sanitize this a little bit. Maybe use
> a
> > simple regex like re.match(r'[a-zA-Z]+', execution_policy) to make sure
> > nobody injects a ; or whatever weird thing that could lead to other even
> > more weird to debug errors.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/AcademySoftwareFoundation/rez/pull/1505#pullrequestreview-1618674621>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ABPOE3QGRU2PLYPOHBHIEX3XZSQZPANCNFSM6AAAAAAZ6ESIMM>
>
> > .
> > You are receiving this because your review was requested.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AcademySoftwareFoundation/rez/pull/1505#issuecomment-1712579752>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJAV5C4AYS4SEMEPGAPSWDXZS4S7ANCNFSM6AAAAAAZ6ESIMM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-09 20:00 UTC, JeanChristopheMorinPerso commented
We could add strixt values, but why not just use a Regen and save us the trouble of having to follow windows/powershell releases?

2023-09-11 18:17 UTC, herronelou commented
I'm fine with either.
The seven PowerShell execution policies are: Default, Restricted, RemoteSigned, AllSigned, Unrestricted, Bypass, and Undefined.
@maxnbk @JeanChristopheMorinPerso you tell me which you prefer and I'll go with it. It doesn't look like policies are updated very frequently, the oldest documentation I can find (powershell 3.0) has the same policies.

2023-09-11 22:47 UTC, JeanChristopheMorinPerso commented
@maxnbk you forgot to add `-s` when you rebased.

2024-01-28 18:51 UTC, JeanChristopheMorinPerso commented
Hi @herronelou , do you think you could follow the instructions at https://github.com/AcademySoftwareFoundation/rez/pull/1505/checks?check_run_id=16687974501 please? I'd like to merge this but we need commits to be signed off. Thanks!

2024-01-28 23:44 UTC, JeanChristopheMorinPerso approved these changes
Thanks! Hopefully that will be enough for when we enable power shell by default in 3.0.

2024-01-28 23:48 UTC, herronelou commented
@JeanChristopheMorinPerso can you confirm if I fixed it fine?

2024-01-28 23:52 UTC, JeanChristopheMorinPerso commented
Yep, it looks fine. The DCO bot says that everything is properly signed off.

2024-02-04 16:05 UTC, merged

2024-02-04 16:05 UTC, JeanChristopheMorinPerso commented
Thanks @herronelou, this will be released in 3.0.