Cleanup backports since we are now Python 3.x+ only
AcademySoftwareFoundation/rez pull request #1634
Opened 2024-02-11 21:55 UTC by BryceGattis

2024-02-12 02:36 UTC, JeanChristopheMorinPerso commented
Can we really replace our lrucache with the built-in one? The one we have has a comment that says that it's modified to make it more performant.

2024-02-15 09:22 UTC, predat commented
> Can we really replace our lrucache with the built-in one? The one we have has a comment that says that it's modified to make it more performant.

As far as I know, lru_cache has had a C implementation since at least python 3.7. I've done a few tests of my own, and functools.lru_cache seems to be at least 3x faster than rez.backport.lru_cache.lru_cache.

2024-02-15 09:35 UTC, predat commented
Do you think this is a good place to also tackle enum ?

2024-02-16 21:37 UTC, JeanChristopheMorinPerso commented
> > Can we really replace our lrucache with the built-in one? The one we have has a comment that says that it's modified to make it more performant.
> 
> As far as I know, lru_cache has had a C implementation since at least python 3.7. I've done a few tests of my own, and functools.lru_cache seems to be at least 3x faster than rez.backport.lru_cache.lru_cache with python 3.11.

Can you share the code you used to run your benchmark? We can also run rez's own benchmark (because yes we have benchmarks).

> Do you think this is a good place to also tackle enum 
@predat enum should go in another PR IMO.

2024-02-16 22:14 UTC, predat commented
> Can you share the code you used to run your benchmark? We can also run rez's own benchmark (because yes we have benchmarks).

```python
@lru_cache(maxsize=1000)
def fib(n):
    return 1 if n in (0, 1) else fib(n - 1) + fib(n - 2)
```

with `from rez.backport.lru_cache import lru_cache`:
```bash
python -m timeit -s 'from fib import fib' 'fib(495)'
5000000 loops, best of 5: 53.9 nsec per loop
```

with `from functools import lru_cache`:
```bash
python -m timeit -s 'from fib import fib' 'fib(495)'
500000 loops, best of 5: 860 nsec per loop
```

2024-02-17 16:11 UTC, JeanChristopheMorinPerso commented on src/rez/vendor/pyparsing/pyparsing.py
We should not touch the vendored modules.

2024-02-17 16:12 UTC, JeanChristopheMorinPerso requested changes
Oups, I wanted to mark it as "request changes". @BryceGattis can you rebase/merge also to resolve the conflict?

2024-02-18 16:13 UTC, BryceGattis commented
Restored `rez/backport/ordereddict.py`  so it can still be used the `src/rez/vendor/pyparsing/pyparsing.py` vendor file. 👍

2024-02-18 17:16 UTC, BryceGattis commented
@JeanChristopheMorinPerso Notes addressed 👍

2024-03-01 17:43 UTC, JeanChristopheMorinPerso approved these changes

2024-03-01 17:45 UTC, merged