Powershell alias return correct exit codes
AcademySoftwareFoundation/rez pull request #1778
Opened 2024-06-21 17:29 UTC by brycegbrazen

Fixes issue where powershell plugins were not correctly capturing exit codes when aliased commands failed.

Closes #1776.

2024-06-21 18:28 UTC, brycegbrazen commented
Looks like Python isn't installed to all of our action VMs? Not sure what other command I could use that's shell agnostic outside of `echo`. I don't think there's a way to make `echo` fail as I need this test to.

2024-06-22 02:49 UTC, JeanChristopheMorinPerso commented
@brycegbrazen these tests are complex, so reuse what's already there and don't call python directly. Look at the `test_command` test. It uses a pre-configured `hello_world` command that I think can be instructed to exit with a specific exit code.

2024-06-22 02:50 UTC, JeanChristopheMorinPerso commented
https://github.com/AcademySoftwareFoundation/rez/blob/main/src%2Frez%2Fbind%2Fhello_world.py#L34

2024-06-22 03:00 UTC, JeanChristopheMorinPerso requested changes

2024-09-19 20:11 UTC, JeanChristopheMorinPerso approved these changes

2024-09-20 08:13 UTC, instinct-vfx approved these changes

2024-09-22 18:35 UTC, merged